### PR TITLE
Add service; Add helper file; Add controller test

### PR DESCRIPTION
**Pull request by jinminhao**
1. Add service creation
2. Add a helper file, putting function of creating resources, creating deployments an creating services into it
3. Acc a controller test file, testing the controller

### CODE REVIEW

**Review by tizhou86 — APPROVED** [review]
paddleflow serving controller would be better than paddle controller in this case.

**Comment by jinminhao** [comment]
1. Change controle file's filename
2. Change to multi group
3. Add pkg folder and put apis and controllers into it

**Review by tizhou86 — COMMENTED** [review]
lgtm

**Review by tizhou86 — COMMENTED** [review]
nvm

**Pull request merged**
